[project]
name = "mcp-scraper"
version = "0.1.0"
description = "CLI Utility for scraping the available resources from an MCP server."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.10.1",
    "typer>=0.16.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.2",
]
